name: chat2
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10.11
  - pip=23.1.2
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  # - conda-forge::transformers
  - pip:
    - accelerate==0.30.0
    - bitsandbytes==0.43.1 
    - python-json-logger==2.0.7
    - pytest==7.4.0
    - pandas==2.0.3 
    - pre-commit==3.3.3
    - black==23.3.0
    - scipy==1.11.1
    - Pillow==10.0.0
    - mlflow==2.6.0
    - boto3==1.28.2
    - scikit-learn==1.3.0
    - pylint==2.17.4
    - pydocstyle==6.3.0
    - pygments==2.15.1
    - semgrep==1.33.2
    - ipykernel==6.25.1
    - fastapi==0.103.0
    - uvicorn[standard]==0.23.2
    - gunicorn==21.2.0
    - pydantic==1.10.12
    - python-multipart==0.0.6
    - jsonlines==3.1.0
    - sphinx==4.3.2
    - omegaconf==2.3.0
    - transformers==4.32.0
    - chainlit
